### ISSUE TITLE
Does not fail the build on exception

### ISSUE THREAD

**Issue by danturn** [EKibort/TeamCityFitnessePlugin#18]
Hi, 

If I get an exception trying to run a test suite (i temporarily was getting a 404 when trying to connect to the suite url), it seems to log the exception but not fail the build. Is this the intended behaviour? I need to fail a build if the tests are not run for whatever reason

here's the corresponding logs from the build:

[14:05:03][Step 10/13] Fitnesse ran
[14:05:03][Step 10/13] Fitnesse starting...
[14:05:03][Step 10/13] 	 response:200
[14:05:03][Step 10/13] 	 response:200
[14:05:03][Step 10/13] Connecting to 'http://localhost:8081/<MYMAGICTESTS>.ApiDocumentation?suite&format=xml'
[14:05:03][Step 10/13] Connected: '404/Not Found'
[14:05:03]
[Step 10/13] java.io.FileNotFoundException: http://localhost:8081/<MYMAGICTESTS>.ApiDocumentation?suite&format=xml
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1675)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1673)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1671)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1244)
	at Fitnesse.agent.FitnesseProcess.getSuiteResults(FitnesseProcess.java:109)
	at Fitnesse.agent.FitnesseProcess.runSuites(FitnesseProcess.java:183)
	at Fitnesse.agent.FitnesseProcess.call(FitnesseProcess.java:209)
	at Fitnesse.agent.FitnesseProcess.call(FitnesseProcess.java:21)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.io.FileNotFoundException: http://localhost:8081/<MYMAGICTESTS>.ApiDocumentation?suite&format=xml
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1624)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at Fitnesse.agent.FitnesseProcess.getSuiteResults(FitnesseProcess.java:107)
	... 7 more

Thanks Dan

**Comment by EKibort** [comment]
I'll try to fix it in a future or you can send pull request. 
Thank you.
