### ISSUE TITLE
Trying to run via teamcity 8.1.2

### ISSUE THREAD

**Issue by benjammin17** [EKibort/TeamCityFitnessePlugin#23]
On the client, I can see the jar start up on port 8080, but then that's it. TC times out after 5 minutes.

Fitnesse: c:\Fitnesse\fitnesse-standalone.jar
Port: 8080
Test or suite relative url: FitNesse.SuiteAcceptanceTests.SuiteWidgetTests.TestBackwardsSearchWidget?test

Step 1/1: Fitnesse runer (5m:02s)
[13:14:43][Step 1/1] FitNesse runner executing.
[13:14:43][Step 1/1] Running fitnesse use cmd 'java -DCCFITDIR="c:\Fitnesse" -jar c:\Fitnesse\fitnesse-standalone.jar -p 8080' in 'c:\Fitnesse'
[13:14:43][Step 1/1] Fitnesse runned java.lang.ProcessImpl@13d95a7d
[13:14:45][Step 1/1] 	[WAIT] Bootstrapping FitNesse, the fully integrated standalone wiki and acceptance testing framework.
[13:19:42][Step 1/1] The build Fitnesse runner #16.07.0.17 {builId=1686574} has been running for more than 5 minutes. Terminating...
[13:19:45][Step 1/1] Dumping threads before termination:
[13:19:45][Step 1/1] PID: 3548, PPID: 2100, Command line: java -DCCFITDIR="c:\Fitnesse" -jar c:\Fitnesse\fitnesse-standalone.jar -p 8080
[13:19:45]
[Step 1/1] 2016-06-17 13:19:02
Full thread dump Java HotSpot(TM) 64-Bit Server VM (24.75-b04 mixed mode):

"Thread-3" prio=6 tid=0x00000000088c3000 nid=0x7bc waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"DestroyJavaVM" prio=6 tid=0x0000000000c1e800 nid=0xc58 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Thread-1" prio=6 tid=0x00000000089ed800 nid=0x590 runnable [0x00000000092bf000]
   java.lang.Thread.State: RUNNABLE
	at java.net.DualStackPlainSocketImpl.accept0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketAccept(Unknown Source)
	at java.net.AbstractPlainSocketImpl.accept(Unknown Source)
	at java.net.PlainSocketImpl.accept(Unknown Source)
	- locked <0x00000000eb312b38> (a java.net.SocksSocketImpl)
	at java.net.ServerSocket.implAccept(Unknown Source)
	at java.net.ServerSocket.accept(Unknown Source)
	at fitnesse.socketservice.SocketService.serviceThread(SocketService.java:60)
	at fitnesse.socketservice.SocketService.access$000(SocketService.java:15)
	at fitnesse.socketservice.SocketService$1.run(SocketService.java:32)
	at java.lang.Thread.run(Unknown Source)

"Service Thread" daemon prio=6 tid=0x0000000006c4a000 nid=0xe3c runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" daemon prio=10 tid=0x0000000006c37000 nid=0xc44 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" daemon prio=10 tid=0x0000000006c33800 nid=0x64 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Attach Listener" daemon prio=10 tid=0x0000000006c32800 nid=0xd74 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" daemon prio=10 tid=0x0000000006c2f000 nid=0xc24 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" daemon prio=8 tid=0x0000000006bfc800 nid=0x628 in Object.wait() [0x0000000007fbf000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000000ece28b50> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(Unknown Source)
	- locked <0x00000000ece28b50> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(Unknown Source)
	at java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)

"Reference Handler" daemon prio=10 tid=0x0000000006bf3800 nid=0xabc in Object.wait() [0x0000000007ebf000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000000ece287a8> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Object.java:503)
	at java.lang.ref.Reference$ReferenceHandler.run(Unknown Source)
	- locked <0x00000000ece287a8> (a java.lang.ref.Reference$Lock)

"VM Thread" prio=10 tid=0x0000000006bef800 nid=0xf78 runnable 

"GC task thread#0 (ParallelGC)" prio=6 tid=0x0000000000c66000 nid=0x7a0 runnable 

"GC task thread#1 (ParallelGC)" prio=6 tid=0x0000000000c68000 nid=0xae0 runnable 

"GC task thread#2 (ParallelGC)" prio=6 tid=0x0000000000c6a000 nid=0xa8c runnable 

"GC task thread#3 (ParallelGC)" prio=6 tid=0x0000000000c6b800 nid=0x5d4 runnable 

"VM Periodic Task Thread" prio=10 tid=0x0000000006c5c800 nid=0xb24 waiting on condition 

[13:19:45][Step 1/1] 
[13:19:45][Step 1/1] Step Fitnesse runer interrupted

**Comment by benjammin17** [comment]
is this project no longer supported?

**Comment by EKibort** [comment]
Hi @benjammin17  ,
This project is supported. 
TeamCity 8.1.2 was release 8 April 2014, and it is very old version for now. Could you try to use latest version. 
Thank you!

**Comment by benjammin17** [comment]
Ekibort - I dont have control over the corporate Teamcity servers, but I can find if they have plans to upgrade.
